### ISSUE TITLE
Problems while downloading the training data

### ISSUE THREAD

**Issue by shangbuhuan13** [zxhuang1698/ZeroShape#4]
Thank you for your excellent work. I met a preblem while downloading the training data combined_synthetic.tar.gz . When I download about 20GB, the browser automatically stops the download, saying the resource is unavailable。 It seems the DropBox can not support that big data.

**Comment by zxhuang1698** [comment]
Thanks for your interest in our work. Please try using tools such as [rclone](https://github.com/rclone/rclone) to download it. Directly wget the link also works if your internet is stable. I have tried both, and they worked for me on several different machines.

**Comment by shangbuhuan13** [comment]
rclone works for me. Thank you very much for your reply.
