### ISSUE TITLE
Some questions about gt_sample_sdf

### ISSUE THREAD

**Issue by QiuJunning** [zxhuang1698/ZeroShape#5]
Hello, I think this work is very interesting and great!!!!!
I have a question about the dataset labeling, I hope you can answer it. I noticed that the true value of occupancy is obtained by reading sample_sdf and subtracting 0.003. I want to know if sample_sdf is the definition of SDF? Why do we need to subtract 0.003? And how can I get this sample_sdf value of a model?
Looking forward to your answer! Thank you!

**Comment by zxhuang1698** [comment]
Thanks for your interest in our work. This offset is related to the data preparation code we are using. We first remove the interior surfaces with virtual scanning (https://github.com/davidstutz/mesh-fusion) and then convert it to SDF query and GT following https://github.com/rehg-lab/3DShapeGen/blob/master/SDFNet/README.md.

**Comment by QiuJunning** [comment]
I can use the above process to remove the internal surface of my object model and then get the SDF label. After executing according to these two repos, I still need to keep the setting of minus 0.003. I don’t know if I understand it correctly?

**Comment by zxhuang1698** [comment]
Yes that is correct.
