### ISSUE TITLE
Is the training data watertight?

### ISSUE THREAD

**Issue by PavanMantripragada** [zxhuang1698/ZeroShape#6]
Hi,

Is the training data provided in this repo watertight?

**Comment by zxhuang1698** [comment]
Yes, that is correct.

**Comment by PavanMantripragada** [comment]
Thanks! I've realized that the dataset provided is directly gt_sdf and their corresponding images, camera parameters. There are no watertight meshes in them. I guess we have to build them on our own if needed.
