### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by PavanMantripragada** [zxhuang1698/ZeroShape#7]
Hi,

I'm trying to train your model jointly by initializing the depth and camera estimator with your given weights and running the following command.

`python train.py --yaml=options/shape.yaml --name=run-shape`

I'm using:
Ubuntu 20.04.06 LTS
Intel Core i9-13900K 5.6 GHz
DDR5-5600 CL28 RAM  - 64 GB
Single GPU - Nvidia GeForce RTX 4090 24 GB

10000 iterations of training takes 1.48 hours 
So, 15 epochs (with 587115 iter per epoch) should take ~1303 hours (54 days)

Can you provide us more implementation details on how the model was trained in ~3 days. 

Thanks!

**Comment by zxhuang1698** [comment]
Hi, we didn't do any additional thing to speed up beyond what's already released. The model was trained on four GPUs instead of one. Your calculation of "587115 iter per epoch" looks odd to me. I believe this is for the total of 15 epochs instead of one.
