### ISSUE TITLE
depth and intrinsics

### ISSUE THREAD

**Issue by liannuaa** [zxhuang1698/ZeroShape#8]
I want to predict the intrinsics and depth map, but the pre-trained model predicts the depth map and visible surfaces, how do I get the camera intrinsics? Thank you very much!

**Comment by zxhuang1698** [comment]
If you take the `var.intr_pred` from the demo.py, that's the predicted intrinsics. However, these intrinsics are not intended to be used on its own without the predicted depth -- they are not directly learned to match the ground truth absolute intrinsics.

**Comment by liannuaa** [comment]
> If you take the `var.intr_pred` from the demo.py, that's the predicted intrinsics. However, these intrinsics are not intended to be used on its own without the predicted depth -- they are not directly learned to match the ground truth absolute intrinsics.

谢谢哥🙏
